server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/todo_api
    username: root
    password: root

grpc:
  port: 6565
  enableReflection: true

mybatis:
  type-aliases-package: chigirh.app.todo.be.todoapi.infra.dto.result
  mapperInterface: chigirh.app.todo.be.todoapi.infra.mapper
